trigger:
 - main

pool: rangent-pool
stages:
  - stage: Terraform Plan
    displayName: Terraform plan
    jobs:
      - job: Terraform plan
        displayName: Terraform plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'xyzconnection'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'xyzconnection'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'xyzconnection'

