trigger:
 branches:
   include:
     - feature/*
     - main

pool: ragent-pool
stages:
  - stage: validate
    displayName: validate
    jobs:
      - job: 
        displayName: validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'xyzconnection'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'xyzcontainer'
              backendAzureRmKey: 'rishiterraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: plan
    displayName: plan
    jobs:
      - job: 
        displayName: plan
        steps:
          - 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'xyzconnection'
    backendAzureRmStorageAccountName: 'pipelinetfstate'
    backendAzureRmContainerName: 'xyzcontainer'
    backendAzureRmKey: 'rishiterraform.tfstate'
    
      

